/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'surface-variant': '#e0e3e5',
                'secondary': '#555f70',
                'surface': '#f7fafc',
                'on-background': '#181c1e',
                'background': '#f7fafc',
                'surface-container-low': '#f1f4f6',
                'tertiary-fixed': '#ffddba',
                'surface-container-highest': '#e0e3e5',
                'on-primary-container': '#86a0cd',
                'error': '#ba1a1a',
                'primary-fixed-dim': '#adc7f7',
                'inverse-on-surface': '#eef1f3',
                'inverse-primary': '#adc7f7',
                'on-error-container': '#93000a',
                'surface-dim': '#d7dadc',
                'surface-container': '#ebeef0',
                'outline': '#74777f',
                'on-secondary': '#ffffff',
                'on-primary-fixed': '#001b3c',
                'on-surface-variant': '#43474e',
                'secondary-fixed': '#d9e3f8',
                'on-tertiary-container': '#c6955e',
                'inverse-surface': '#2d3133',
                'surface-bright': '#f7fafc',
                'tertiary-container': '#4f2e00',
                'on-secondary-fixed': '#121c2b',
                'primary': '#002045',
                'surface-container-lowest': '#ffffff',
                'on-surface': '#181c1e',
                'surface-container-high': '#e5e9eb',
                'on-tertiary': '#ffffff',
                'tertiary-fixed-dim': '#f2bc82',
                'secondary-fixed-dim': '#bdc7db',
                'on-tertiary-fixed-variant': '#633f0f',
                'outline-variant': '#c4c6cf',
                'on-tertiary-fixed': '#2b1700',
                'surface-tint': '#455f88',
                'tertiary': '#321b00',
                'secondary-container': '#d9e3f8',
                'on-secondary-fixed-variant': '#3e4758',
                'on-secondary-container': '#5b6577',
                'primary-fixed': '#d6e3ff',
                'on-primary-fixed-variant': '#2d476f',
                'primary-container': '#1a365d',
                'on-primary': '#ffffff',
                'error-container': '#ffdad6',
                'on-error': '#ffffff',
            },
            fontFamily: {
                'headline': ['Manrope'],
                'body': ['Inter'],
                'label': ['Inter'],
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
        },
    },
};

// export default {
//     darkMode: "class",
//     theme: {
//         extend: {
//             colors: {
//                 "secondary": "#1960a3",
//                 "outline-variant": "#c4c6cf",
//                 "secondary-fixed-dim": "#a2c9ff",
//                 "secondary-fixed": "#d3e4ff",
//                 "background": "#f7f9fb",
//                 "on-tertiary": "#ffffff",
//                 "on-secondary": "#ffffff",
//                 "surface-container-high": "#e6e8ea",
//                 "on-secondary-fixed-variant": "#004881",
//                 "on-primary-fixed": "#001b3c",
//                 "tertiary-container": "#27374b",
//                 "error-container": "#ffdad6",
//                 "inverse-on-surface": "#eff1f3",
//                 "primary-fixed": "#d6e3ff",
//                 "primary": "#002045",
//                 "inverse-surface": "#2d3133",
//                 "tertiary-fixed": "#d3e4fe",
//                 "on-primary": "#ffffff",
//                 "surface": "#f7f9fb",
//                 "surface-variant": "#e0e3e5",
//                 "on-tertiary-container": "#90a0b9",
//                 "tertiary": "#112235",
//                 "surface-bright": "#f7f9fb",
//                 "surface-container": "#eceef0",
//                 "on-error": "#ffffff",
//                 "on-secondary-fixed": "#001c38",
//                 "inverse-primary": "#adc7f7",
//                 "on-background": "#191c1e",
//                 "surface-tint": "#455f88",
//                 "primary-fixed-dim": "#adc7f7",
//                 "on-primary-fixed-variant": "#2d476f",
//                 "surface-dim": "#d8dadc",
//                 "error": "#ba1a1a",
//                 "secondary-container": "#7db6ff",
//                 "surface-container-lowest": "#ffffff",
//                 "on-surface-variant": "#43474e",
//                 "outline": "#74777f",
//                 "on-secondary-container": "#00477f",
//                 "tertiary-fixed-dim": "#b7c8e1",
//                 "surface-container-low": "#f2f4f6",
//                 "on-error-container": "#93000a",
//                 "surface-container-highest": "#e0e3e5",
//                 "on-tertiary-fixed": "#0b1c30",
//                 "on-tertiary-fixed-variant": "#38485d",
//                 "on-primary-container": "#86a0cd",
//                 "primary-container": "#1a365d",
//                 "on-surface": "#191c1e",
//             },
//             borderRadius: {
//                 "DEFAULT": "0.25rem",
//                 "lg": "0.5rem",
//                 "xl": "0.75rem",
//                 "full": "9999px",
//             },
//             "fontFamily": {
//                 "headline": ["Manrope"],
//                 "body": ["Inter"],
//                 "label": ["Inter"],
//             },
//         },
//     },
// };
