/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'surface-variant': '#e0e3e5',
                'secondary': '#555f70',
                'surface': '#f7fafc',
                'on-background': '#181c1e',
                'background': '#f7fafc',
                'surface-container-low': '#f1f4f6',
                'tertiary-fixed': '#ffddba',
                'surface-container-highest': '#e0e3e5',
                'on-primary-container': '#86a0cd',
                'error': '#ba1a1a',
                'primary-fixed-dim': '#adc7f7',
                'inverse-on-surface': '#eef1f3',
                'inverse-primary': '#adc7f7',
                'on-error-container': '#93000a',
                'surface-dim': '#d7dadc',
                'surface-container': '#ebeef0',
                'outline': '#74777f',
                'on-secondary': '#ffffff',
                'on-primary-fixed': '#001b3c',
                'on-surface-variant': '#43474e',
                'secondary-fixed': '#d9e3f8',
                'on-tertiary-container': '#c6955e',
                'inverse-surface': '#2d3133',
                'surface-bright': '#f7fafc',
                'tertiary-container': '#4f2e00',
                'on-secondary-fixed': '#121c2b',
                'primary': '#002045',
                'surface-container-lowest': '#ffffff',
                'on-surface': '#181c1e',
                'surface-container-high': '#e5e9eb',
                'on-tertiary': '#ffffff',
                'tertiary-fixed-dim': '#f2bc82',
                'secondary-fixed-dim': '#bdc7db',
                'on-tertiary-fixed-variant': '#633f0f',
                'outline-variant': '#c4c6cf',
                'on-tertiary-fixed': '#2b1700',
                'surface-tint': '#455f88',
                'tertiary': '#321b00',
                'secondary-container': '#d9e3f8',
                'on-secondary-fixed-variant': '#3e4758',
                'on-secondary-container': '#5b6577',
                'primary-fixed': '#d6e3ff',
                'on-primary-fixed-variant': '#2d476f',
                'primary-container': '#1a365d',
                'on-primary': '#ffffff',
                'error-container': '#ffdad6',
                'on-error': '#ffffff',
            },
            fontFamily: {
                'headline': ['Manrope'],
                'body': ['Inter'],
                'label': ['Inter'],
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
        },
    },
};
